### ISSUE TITLE
(Pandas) ValueError: invalid literal for int() with base 10: '0x2987'

### ISSUE THREAD

**Issue by rudongsu** [msep2019/MSEP_2019_1#98]
error occurs when trying to change the data type from object to int:

`dt[["Dport"]] = dt[["Dport"]].astype('int64')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "E:\PyCharm Community Edition 2019.2.1\CIDDS\venv\lib\site-packages\pandas\core\generic.py", line 5882, in astype
    dtype=dtype, copy=copy, errors=errors, **kwargs
  File "E:\PyCharm Community Edition 2019.2.1\CIDDS\venv\lib\site-packages\pandas\core\internals\managers.py", line 581, in astype
    return self.apply("astype", dtype=dtype, **kwargs)
  File "E:\PyCharm Community Edition 2019.2.1\CIDDS\venv\lib\site-packages\pandas\core\internals\managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)
  File "E:\PyCharm Community Edition 2019.2.1\CIDDS\venv\lib\site-packages\pandas\core\internals\blocks.py", line 559, in astype
    return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)
  File "E:\PyCharm Community Edition 2019.2.1\CIDDS\venv\lib\site-packages\pandas\core\internals\blocks.py", line 643, in _astype
    values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)
  File "E:\PyCharm Community Edition 2019.2.1\CIDDS\venv\lib\site-packages\pandas\core\dtypes\cast.py", line 707, in astype_nansafe
    return lib.astype_intsafe(arr.ravel(), dtype).reshape(arr.shape)
  File "pandas\_libs\lib.pyx", line 547, in pandas._libs.lib.astype_intsafe
ValueError: invalid literal for int() with base 10: '0x2987'`

**Comment by rudongsu** [comment]
the issue solved by using pandas .apply method:
`data["Dport"] = data["Dport"].apply(pd.to_numeric, errors='coerce')
`
instead of 
`data[["Dport"]] = data[["Dport"]].astype(int)
`
